config/routes.rb
Rails.application.routes.draw do
  get 'playlist_items/create'
  root to: "readings#index"

  devise_for :users
  resources :users, only: [:index, :show]
  resources :book_stores, only: [:index]
  resources :friend_relationships, only: [:create, :destroy]

  resources :playlists, except: [:new, :edit]

  resources :books, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:index, :create]
    resources :suggestions, only: [:create]
  end

  resources :suggestions, only: [:index]

  resources :readings, only: [:new, :index, :show, :update, :destroy, :create] do
    resources :playlist_items, only: [:create]
  end

  get 'discovers', to: 'discovers#index'

  get 'wishlist', to: 'suggestions#wishlist'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/discovers_controller.rb
class DiscoversController < ApplicationController
  def index
    @suggestions = Suggestion.where(user: current_user).where.not(sender_id: current_user.id)
    @wishlist = Suggestion.where(sender_id: current_user.id)
    @books = Book.all
    @users = User.all
  end
end

app/views/discovers/index.html.erb
<% @title = "Découvrir" %>

<div class="container">
<%= link_to suggestions_path do %>
<h3 class="px-3">Suggestions de mes amis</h3>
<% end %>
<div class="container-detail gap1">
      <% @suggestions.first(6).each do |suggestion| %>
        <%= link_to book_path(suggestion.book) do %>
          <div class="cards-playlist white-background">
            <%= image_tag suggestion.book.image_url, class: "image-book" %>
            <h1><%= suggestion.book.title %></h1>
            <p><%= suggestion.book.author %></p>
          </div>
        <% end %>
      <% end %>
    </div>

<h3 class="px-3">Mes recommandations</h3>
<div class="container-detail gap1">
    <% current_user.recs_books.first(10).each do |recommandation| %>
      <%= link_to book_path(recommandation[:book]) do %>
      <div class="cards-playlist white-background">
        <%= image_tag recommandation[:book].image_url, class: "image-book" %>
        <h1><%= recommandation[:book].title %></h1>
        <p><%= recommandation[:book].author %></p>
        <p><%= recommandation[:similarity].to_i %>% de<br>correspondance<br>avec votre profil</p>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= link_to wishlist_path do %>
<h3 class="px-3">Ma liste de souhaits</h3>
<% end %>
<div class="container-detail gap1">
      <% @wishlist.first(6).each do |wish| %>
          <%= link_to book_path(wish.book) do %>
            <div class="cards-playlist white-background">
              <%= image_tag wish.book.image_url, class: "image-book" %>
              <h1><%= wish.book.title %></h1>
              <p><%= wish.book.author %></p>
            </div>
          <% end %>
        <% end %>
    </div>
</div>

<%= link_to books_path do %>
<h3 class="px-3">Une infinité d'ouvrages à découvrir...</h3>
<% end %>
<div class="container-detail gap1">
  <% @books.first(6).each do |book| %>
      <%= link_to book_path(book) do %>
        <div class="cards-playlist white-background">
          <%= image_tag book.image_url, class: "image-book" %>
          <h1><%= book.title %></h1>
          <p><%= book.author %></p>
        </div>
      <% end %>
  <% end %>
</div>

<%= link_to users_path do %>
<h3 class="px-3">Les utilisateur.ices de Bouquinotheque</h3>
<% end %>
<div class="container-detail gap1">
  <% @users.first(6).each do |user| %>
      <%= link_to user_path(user) do %>
        <div class="cards-playlist white-background">
          <%= image_tag user.avatar, class: "image-book", style: "width:150px; height: 150px" %>
          <h1><%= user.nickname %></h1>
          <p><%= user.age %> ans, <%= user.city %></p>
        </div>
      <% end %>
  <% end %>
</div>