config/routes.rb
Rails.application.routes.draw do
  get 'playlist_items/create'
  root to: "readings#index"

  devise_for :users
  resources :users, only: [:index, :show]
  resources :book_stores, only: [:index]
  resources :friend_relationships, only: [:create, :destroy]

  resources :playlists, except: [:new, :edit]

  resources :books, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:index, :create]
    resources :suggestions, only: [:create]
  end

  resources :suggestions, only: [:index]

  resources :readings, only: [:new, :index, :show, :update, :destroy, :create] do
    resources :playlist_items, only: [:create]
  end

  get 'discovers', to: 'discovers#index'

  get 'wishlist', to: 'suggestions#wishlist'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  require 'matrix'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :playlists, dependent: :destroy
  has_many :suggestions, dependent: :destroy
  has_many :readings, dependent: :destroy
  has_many :friend_relationships, dependent: :destroy
  validates :nickname, presence: true
  validates :city, presence: true

  def user_profile
    Vector[self.thriller_score, self.romance_score, self.aventure_score, self.jeunesse_score]
  end


  def update_user_profil_recommandation(new_rating_vector)
  #mean of user profile and weighted new item review
  # Vold = current user profile
  #Vnew = new user profile after rating is factored in
  #Vitem = vector representation of item being review
  #If the review is favorable, use it to calculate new mean
  #If review was negative, use the inverse vector to calculate new mean
  #ex - If a user profile consists of 5 reviews, the effect of a 6th would
  #looks like this:
  #(5 x Vold + Vitem)/6
  #formula: Vnew = ((n x Vold) + Vitem )/ n + 1

  # new_vector_thriller = (@total_reviews * @user_profile[0] + new_rating_vector[0])/(@total_reviews + 1)
  # new_vector_romance = (@total_reviews * @user_profile[1] + new_rating_vector[1])/(@total_reviews + 1)
  # new_vector_aventure = (@total_reviews * @user_profile[2] + new_rating_vector[2])/(@total_reviews + 1)
  # new_vector_jeunesse = (@total_reviews * @user_profile[3] + new_rating_vector[3])/(@total_reviews + 1)

  @total_reviews = Reading.where(user: self).where.not(my_rating: nil).size
    self.thriller_score = (@total_reviews * self.thriller_score + new_rating_vector[0])/(@total_reviews + 1)
    self.romance_score = (@total_reviews * self.romance_score + new_rating_vector[1])/(@total_reviews + 1)
    self.aventure_score = (@total_reviews * self.aventure_score + new_rating_vector[2])/(@total_reviews + 1)
  @user_profile = user_profile()
  return @user_profile
  end

  def similarity_score(book)
    # create a vector for the user the method is being called on
    # attributes needed are board_score, card_score, party_score and players_score
    user_vector = user_profile()
    # next, create a vector for the game being passed in to the method
    # we will then compare the two vectors to see how similar the books are
    book_vector = Vector[book.thriller_score, book.romance_score, book.aventure_score, book.jeunesse_score]
    # now that we have 2 vectors we will find the similarity by putting the dot product in our numerator, and the product of each vectors magnitude in our denominator
    numerator = user_vector.inner_product(book_vector)
    denominator = user_vector.r * book_vector.r
    # this will give the cosine similarity
    score = numerator / denominator*100
    return score
  end

  def recs_books
    book_ids = self.readings.map(&:book_id)
    book_rec_array = []
    user_profile()
    Book.where.not(id: book_ids).each do |book|
      score = similarity_score(book)
      book_rec_array.push( { book: book, similarity: score } )
    end
    book_rec_array.sort_by{|rec| -rec[:similarity]}
  end

  def update_recommandation_score(new_rating_vector)
    self.update_user_profil_recommandation(new_rating_vector)
  end

  def friends
    friend_ids = (self.friend_relationships.map(&:friend_id) + FriendRelationship.where(friend_id: self.id).map(&:user_id))
    User.where(id: friend_ids)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @new_friend = FriendRelationship.new

    @friends = @user.friends
  end
end

app/views/users/_friend_relationship_partial.html.erb
<% collection.each do |friend| %>
  <%= link_to user_path(friend), class: "friend", data: {remove_whitespaces_target: "block"} do %>
    <div style="text-align:center">
      <%= image_tag friend.avatar, alt: friend.nickname, class: "avatar" %>
      <h4>
        <%= friend.nickname %>
        <% if @user == current_user %>
          <%= link_to friend_relationship_path(friend: friend), data: { turbo_method: :delete, turbo_confirm: "Êtes vous sûr.e" } do %>
            <i class="fa-solid fa-xmark"></i>
          <% end %>
        <% end %>
      </h4>
    </div>
  <% end %>
<% end %>

app/views/users/index.html.erb
<% @title = "Les utilisateur.ice.s de Bouquinotheque" %>
<div class="container p-3 d-flex flex-wrap gap1 justify-content-between">
  <% @users.each do |user| %>
    <%= link_to user_path(user), style: "width: calc(50% - 0.5rem); border: 2.5px solid #86BBD8", class:"white-background" do %>
      <center>
        <%= image_tag user.avatar, class: "avatar" %>
        <h2>
        <%= user.nickname %>
        </h2>
        <p><%= user.age %> ans, <%= user.city %></p>
      </center>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<% @title = @user.nickname %>

<div class="container d-flex profile m-3">
<%= image_tag @user.avatar, alt: @user.nickname, class: "profile-avatar"%>
<div class="white-background d-flex justify-content-center flex-column ms-3" style="width: 100%;gap: 0.5rem">
      <p><i class="fa-solid fa-cake-candles"></i> <%= @user.age %> ans</p>
      <p><i class="fa-solid fa-city"></i> <%= @user.city %></p>
    </div>
</div>

<center><% if @user != current_user && !@friends.include?(current_user) %>
  <%= simple_form_for @new_friend do |f| %>
    <%= f.input :friend_id, :as => :hidden, :input_html => { :value => current_user.id }  %>
    <%= f.input :user_id, :as => :hidden, :input_html => { :value => @user.id }  %>
    <%= f.button :submit, "Ajouter en ami.e", class: "btn btn-warning" %>
  <% end %>
<% end %></center>

<% if @friends.length != 0 %>
  <h3 class="m-3">Ami.e.s</h3>
  <div data-controller="display-all remove-whitespaces" class="white-background container mx-3">
    <div data-display-all-target="summary">
      <div class="d-flex gap1 justify-content-evenly">
        <%= render 'friend_relationship_partial', collection: @friends[0,3] %>
      </div>
      <center><a data-action="click->display-all#displaySummary" data-display-all-target="summary">afficher davantage d'ami.e.s</a></center>
    </div>
    <div class="d-none" data-display-all-target="summary_all">
      <div class="d-flex gap1 justify-content-evenly flex-wrap">
        <%= render 'friend_relationship_partial', collection: @friends %>
      </div>
      <center><a data-action="click->display-all#displaySummary" data-display-all-target="summary">afficher moins d'ami.e.s</a></center>
    </div>
  </div>
<% end %>