config/routes.rb
Rails.application.routes.draw do
  get 'playlist_items/create'
  root to: "readings#index"

  devise_for :users
  resources :users, only: [:index, :show]
  resources :book_stores, only: [:index]
  resources :friend_relationships, only: [:create, :destroy]

  resources :playlists, except: [:new, :edit]

  resources :books, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:index, :create]
    resources :suggestions, only: [:create]
  end

  resources :suggestions, only: [:index]

  resources :readings, only: [:new, :index, :show, :update, :destroy, :create] do
    resources :playlist_items, only: [:create]
  end

  get 'discovers', to: 'discovers#index'

  get 'wishlist', to: 'suggestions#wishlist'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_bottom_navbar.html.erb
<div class="bottom-navbar">
<div><%= link_to readings_path do %>
<i class="fa-solid fa-book-open"></i>
Bibliothèque
<% end %></div>
<div><%= link_to playlists_path do %>
<i class="fa-solid fa-heart"></i>
Favoris
<% end %></div>
<div><%= link_to discovers_path do %>
<i class="fa-solid fa-globe"></i>
Découvrir
<% end %></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.avatar if current_user.avatar %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
    <h1><%= title %></h1>
  </div>
</div>