config/routes.rb
Rails.application.routes.draw do
  get 'playlist_items/create'
  root to: "readings#index"

  devise_for :users
  resources :users, only: [:index, :show]
  resources :book_stores, only: [:index]
  resources :friend_relationships, only: [:create, :destroy]

  resources :playlists, except: [:new, :edit]

  resources :books, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:index, :create]
    resources :suggestions, only: [:create]
  end

  resources :suggestions, only: [:index]

  resources :readings, only: [:new, :index, :show, :update, :destroy, :create] do
    resources :playlist_items, only: [:create]
  end

  get 'discovers', to: 'discovers#index'

  get 'wishlist', to: 'suggestions#wishlist'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book.rb
require 'matrix'

class Book < ApplicationRecord
  has_many :readings
  has_many :suggestions
  has_many :reviews

  validates :title, presence: true
  validates :author, presence: true
  # validates :genre, presence: true
  validates :publisher, presence: true
  validates :publishing_year, presence: true
  validates :summary, presence: true
  validates :EAN, presence: true
  # validates :ratings, presence: true
  # validates :book_type, presence: true
  validates :image_url, presence: true
  before_validation :set_default_image_url

  scope :filter_by_genre, ->(genre) { where(genre: genre) }
  scope :filter_by_author, ->(author) { where(author: author) }

  def similarity_score_book(book)
    vector_a = Vector[self.thriller_score, self.romance_score, self.aventure_score, self.jeunesse_score]
    #next, create a vector for the game being passed in to the method
    #we will then compare the two vectors to see how similar the games are
    vector_b = Vector[book.thriller_score, book.romance_score, book.aventure_score, book.jeunesse_score]
    #now that we have 2 vectors we will find the similarity by putting the dot product
    #in our numerator, and the product of each vectors magnitude in our denominator
    numerator = vector_a.inner_product(vector_b)
    denominator = vector_a.r * vector_b.r
    #this will give the cosine similarity
    score = numerator / denominator * 100
    return score.to_i
    #since cosine is a decimal between 0 and 1, multiplying by 100 and then rounding to the nearest integer gives a nice scoring system from 0 to 100
  end

  def new_rating_vector
    Vector[self.thriller_score, self.romance_score, self.aventure_score, self.jeunesse_score]
  end

  def isbn
    return ISBN.ten(self.EAN.strip)
  end

  def set_default_image_url
    self.image_url ||= default_image_url if image_url.blank?
  end

  def default_image_url
    "https://i.imgur.com/BaQcS05.png"
  end
end

app/controllers/books_controller.rb
require "open-uri"
require "json"
require "date"

class BooksController < ApplicationController

  def index
    @books = Book.all

    @genres = Book.pluck(:genre).uniq.sort
    @authors = Book.pluck(:author).uniq.sort

    @books = Book.filter_by_genre(params[:genre]) if params[:genre].present?
    @books = Book.filter_by_author(params[:author]) if params[:author].present?

    case params[:tri]
    when "titleaz" then @books = @books.order(:title)
    when "titleza" then @books = @books.order(title: :desc)
    when "authoraz" then @books = @books.order(:author)
    when "authorza" then @books = @books.order(author: :desc)
    else @books = @books.order(:title)
    end

    respond_to do |format|
      format.html
      format.text { render partial: "books/book_partial", locals: {books: @books}, formats: [:html] }
    end
  end

  def show
    @new_reading = Reading.new
    @book = Book.find(params[:id])
    @new_suggestion = Suggestion.new
    @friends = current_user.friends
    @reading = Reading.find_by(book: @book, user: current_user)
  end

  def new
    result = JSON.parse(URI.open("https://www.googleapis.com/books/v1/volumes?q=isbn:#{params[:EAN]}").read)
    volume_id = result.dig("items", 0, "id")
    if volume_id.nil? || params[:EAN].blank?
      flash.alert = "Entrez un code EAN valide"
      redirect_to new_reading_path
    else
      book_form = JSON.parse(URI.open("https://www.googleapis.com/books/v1/volumes/#{volume_id}").read)
      begin
        publishing_year = DateTime.parse(book_form["volumeInfo"]["publishedDate"]).year
      rescue ArgumentError
        publishing_year = "#{book_form['volumeInfo']['publishedDate']}"
      end
      title = book_form["volumeInfo"]["title"]
      author = book_form["volumeInfo"]["authors"]
      summary = book_form["volumeInfo"]["description"]
      publisher = book_form["volumeInfo"]["publisher"]
      genre = book_form["volumeInfo"]["categories"]
      image_url = book_form["volumeInfo"]["imageLinks"] ? book_form["volumeInfo"]["imageLinks"]["thumbnail"] : "https://i.imgur.com/BaQcS05.png"
      thriller_score = rand(0..10)
      romance_score = rand(0..10)
      aventure_score = rand(0..10)
      jeunesse_score = rand(0..10)
      @book = Book.new(title: title, author: author, summary: summary, publisher: publisher, publishing_year: publishing_year, genre: genre, EAN: params[:EAN], image_url: image_url)
    end
  end

  def create
    @book = Book.new(book_params)
    @book.thriller_score = rand(0..10)
    @book.romance_score = rand(0..10)
    @book.aventure_score = rand(0..10)
    @book.jeunesse_score = rand(0..10)
    if @book.save
      Reading.create(user: current_user, book: @book)
      redirect_to readings_path(@readings)
    else
      redirect_to new_book_path(book_params)
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :summary, :publisher, :publishing_year, :genre, :EAN, :image_url)
  end
end

app/views/books/_book_partial.html.erb
<% books.each do |book| %>
  <%= link_to book_path(book), class:"book-card mb-3" do %>
    <div class="card-content d-flex" style="width:100%">
      <%= image_tag book.image_url, alt: book.title, class: "card-image" %>
      <div>
        <h1><%= book.title %></h1>
        <p><%= book.author %></p>
        <div class="ratings">
          <i class="fa-solid fa-star"></i><%= book.ratings %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/books/index.html.erb
<% @title = "Librairie" %>
<div data-controller="update-filters-input">
  <div class="container">
    <%= form_with url: books_path, method: :get, html: {class: "d-flex mt-3 justify-content-evenly", data: {update_filters_input_target: "form"}} do |f| %>
      <div>
        <%= select_tag :tri,
          options_for_select([['Titre A - Z',"titleaz"], ['Titre Z - A',"titleza"], ['Auteur.ice A - Z',"authoraz"], ['Auteur.ice Z - A',"authorza"]], params[:tri]),
          include_blank: "↑↓", class: "form-control", style: "width: 50px", data: { update_filters_input_target: "inputTri", action: "change->update-filters-input#triB" } %>
      </div>
      <div>
        <%= f.text_field :genre, placeholder: "Genre", style: "width: 125px", class: "form-control", list: "genre-select", data: {update_filters_input_target: "inputGenre", action: "keyup->update-filters-input#genreB"} %>
          <datalist id="genre-select">
            <% @genres.each do |genre| %>
            <option value="<%= genre %>"><%= genre %></option>
            <% end %>
          </datalist>
      </div>
      <div>
        <%= f.text_field :author, placeholder: "Auteur.ice.s", style: "width: 125px", class: "form-control", list: "author-select", data: {update_filters_input_target: "inputAuthor", action: "keyup->update-filters-input#authorB"} %>
          <datalist id="author-select">
            <% @authors.each do |author| %>
              <option value="<%= author %>"><%= author %></option>
            <% end %>
          </datalist>
      </div>
    <% end %>
  </div>

  <div class="container p-3" data-update-filters-input-target="books">
    <%= render 'book_partial', books: @books %>
  </div>
</div>

app/views/books/new.html.erb
<div class="container white-background my-3"><center><h1>Ajouter un nouveau livre</h1></center>
<%= simple_form_for @book do |f| %>
  <%= f.input :title, label: "Titre" %>
  <%= f.input :summary, as: :text, label: "Résumé" %>
  <%= f.input :author, label: "Auteur.ice.s" %>
  <%= f.input :book_type, label: "Type d'ouvrage" %>
  <%= f.input :genre, label: "Genre" %>
  <%= f.input :publisher, label: "Maison d'édition" %>
  <%= f.input :publishing_year, label: "Première année d'édition" %>
  <%= f.input :ratings, label: "Note" %>
  <%= f.input :EAN, label: "EAN" %>
  <%= f.input :image_url, label: "Première de couverture" %>
  <%= f.button :submit, "Ajouter", class: "btn btn-danger"
  %>
<% end %></div>

app/views/books/show.html.erb
<% @title = @book.title %>
<div class="container book-show">
   <div class="h3">
      <%= @book.author %>
      <h4><%= @book.ratings %><i class="fa-solid fa-star"></i></h4>
   </div>
   <div class="white-background">
      <%= image_tag @book.image_url, alt: @book.title, class: "book-cover"%>
      <ul>
         <li><% if @book.publisher.present? %>
         <%= @book.publisher %>,
         <% end %><%= @book.publishing_year %></li>
         <li><% if @book.book_type.present? %>
         <%= @book.book_type&.capitalize %>:
         <% end %>
         <%= @book.genre %>
         </li>
      </ul>
      <div data-controller="display-all" class="summary">
         <p data-display-all-target="summary">
            <%= @book.summary.truncate(200, separator: ' ') %>
            <a data-action="click->display-all#displaySummary">lire plus</a>
         </p>
         <p data-display-all-target="summary_all" class="d-none">
            <%= @book.summary %>
            <a data-action="click->display-all#displaySummary">lire moins</a>
         </p>
      </div>
   </div>
   <center>
   <% if !@reading.present? %>
      <%= simple_form_for @new_reading do |f| %>
        <%= f.input :book_id, :as => :hidden, :input_html => { :value => @book.id }  %>
        <%= f.button :submit, "Ajouter à ma bibliothèque", class: "btn btn-warning mb-3" %>
      <% end %>
      <%= simple_form_for [@book, @new_suggestion] do |f| %>
    <%= f.input :sender_id, :as => :hidden, :input_html => { :value => current_user.id } %>
    <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
    <%= f.input :comment, :as => :hidden, :input_html => { :value => "wish" }  %>
    <%= f.button :submit, "Ajouter à ma liste de souhaits", class: "btn btn-warning mb-3" %>
  <% end %>
  <% end %>
  <div data-controller="display-all"><a data-display-all-target="button" class="btn btn-warning mt-3" data-action="click->display-all#displayForm">Suggérer à un.e ami.e</a>
  <%= simple_form_for [@book, @new_suggestion], html: { data: { display_all_target: "form"}, class: "d-none" } do |f| %>
    <%= f.input :sender_id, :as => :hidden, :input_html => { :value => current_user.id }  %>
    <%= f.input :user_id, label: false, as: :select, collection: @friends.map { |friend| [friend.nickname, friend.id] }, include_blank: false %>
    <%= f.input :comment, label: "Commentaire" %>
    <%= f.button :submit, "Suggérer", data: { display_all_target: "button", action: "click->display-all#displayForm"} %>
  <% end %>
  </div>
      <h3 class="my-6 box-shadow">Avis des lecteur.ice.s</h3>
        <div class="book-reviews">
          <% @book.reviews[0,2].each do |review| %>
          <div class="book-review" style="width: calc(50% - 0.5rem)">
              <div class="h3">
                <%= review.title %>
                <h6>
                    <%= review.rating %>
                    /5
                </h6>
              </div>
              <p>
                <%= review.content %>
              </p>
          </div>
          <% end %>
        </div>
      <%= link_to "Lire davantage d'avis", book_reviews_path(@book), class: "btn btn-warning mb-3"%>
  </center>
<div class="d-flex justify-content-center flex-column align-items-center">
   <h3 class="box-shadow">Acheter cet ouvrage</h3>
   <div class="container d-flex gap-4 my-3 ">
    <a href='https://www.amazon.fr/<%= @book.title %>/dp/<%= @book.isbn%>'><img src="https://i.imgur.com/Qwfo1tK.png" class="avatar-icon avatar mb-3"></a>
    <%= image_tag "https://i.imgur.com/VSWATo5.png", class: "avatar-icon avatar mb-3" %>
    <%= image_tag "https://i.imgur.com/Rm4E7lA.png", class: "avatar-icon avatar mb-3" %>
   </div>
   <%= link_to "Librairies à proximité de #{current_user.city}", book_stores_path, class: "btn btn-warning mb-3" %>
</div>
</div>